Default: &defaults
  host: "*4" # any IPv4 host
  port: 3331
  approot: "http://kawasemi.swlab.cs.okayama-u.ac.jp:3331"
  copyright: Nomura Laboratory (C)
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  #approot: "http://www.example.com"
  <<: *defaults
