Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://localhost"
  copyright: Nomura Laboratory (C)
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  host: "*4" # any IPv4 host
  port: 54321
  approot: "http://www.swlab.cs.okayama-u.ac.jp"
  copyright: Nomura Laboratory (C)
  #analytics: UA-YOURCODE

